apiVersion: v1
kind: PersistentVolume
metadata:
  name: naz-mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /tmp/mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: naz-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: naz-mysql-deployment
spec:
  serviceName: naz-mysql-service
  replicas: 1
  selector:
    matchLabels:
      app: naz-mysql
  template:
    metadata:
      labels:
        app: naz-mysql
    spec:
      containers:
        - name: naz-mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: naz-mysql-secrets
                  key: root-password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: naz-mysql-config
                  key: mysql-database
          ports:
            - containerPort: 3306
          imagePullPolicy: Always
          volumeMounts:
            - name: naz-mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: naz-mysql-persistent-storage
          persistentVolumeClaim:
            claimName: naz-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: naz-mysql-service
spec:
  selector:
    app: naz-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: naz-mysql-config
data:
  mysql-database: sparklmsdb
