---
- name: Downloading Dependencies in AWS
  hosts: aws
  become: true
  roles:
    - aws_setup

- name: Modify application.properties in AWS
  hosts: localhost
  become: true
  connection: local
  gather_facts: false
  roles:
    - local-edit
