- name: Copy JAR file to remote EC2 host
  copy:
    src: /var/lib/jenkins/workspace/AWS-Deploy/target/spark-lms-0.0.1-SNAPSHOT.jar
    dest: /home/ec2-user/
    mode: 0644
    
- name: Restart BJIT App Service
  systemd:
    name: bjit-app.service
    state: restarted
