- name: Install Java 11 (Amazon Corretto)
  package:
    name: java-11-amazon-corretto
    state: present
  when:
    - ansible_distribution == "Fedora" or ansible_os_family == "Amazon"

- name: Set Java version using alternatives
  command: alternatives --auto java
  when:
    - ansible_distribution == "Fedora" or ansible_os_family == "Amazon"

- name: Install MariaDB 10.5
  package:
    name: mariadb105
    state: present
  when:
    - ansible_distribution == "Fedora" or ansible_os_family == "Amazon"

- name: Check if BJIT App Service unit file exists
  stat:
    path: /etc/systemd/system/bjit-app.service
  register: bjit_app_service_file

- name: Create BJIT App Service unit file
  copy:
    content: |
      [Unit]
      Description=BJIT App Service
      After=network.target

      [Service]
      ExecStart=java -jar /home/ec2-user/spark-lms-0.0.1-SNAPSHOT.jar
      WorkingDirectory=/home/ec2-user/
      Restart=on-failure
      User=ec2-user

      RestartSec=10sec

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/bjit-app.service
    mode: 0644
  when: not bjit_app_service_file.stat.exists

- name: Reload Systemd configuration
  systemd:
    daemon_reload: yes